### ISSUE TITLE
Please update to the latest version of ytdl-core.

### ISSUE THREAD

**Issue by Weirdo914** [amishshah/ytdl-core-discord#104]
ytdl-core 0.29.7 is a requirement so this error arises.

```internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/rbd/pnpm-volume/82634606-d46f-49f6-bbcd-c9fd1a77fe11/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)```

**Comment by PropreCity** [comment]
Same here
