### ISSUE TITLE
Undefined 'url' when trying to play blocked video

### ISSUE THREAD

**Issue by eritislami** [amishshah/ytdl-core-discord#195]
Error occurs when trying to play a video that is blocked in my country
Example used: https://www.youtube.com/watch?v=0WV-MV18JCU

I believe it should have properly thrown an error saying the video is blocked instead of hanging
Tested on Node.js v12.16.1 with master branch

```
(node:12376) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at /Users/eritislami/evobot/node_modules/ytdl-core-discord/index.js:40:41
    at /Users/eritislami/evobot/node_modules/ytdl-core-discord/node_modules/ytdl-core/lib/info.js:288:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by eritislami** [comment]
In the same environment & test ytdl-core@3.1.1 properly rejects with 'Video unavailable'
```
Error: input stream: Video unavailable
    at Object.exports.playError (/Users/eritislami/evobot/node_modules/ytdl-core/lib/util.js:441:12)
    at downloadFromInfoCallback (/Users/eritislami/evobot/node_modules/ytdl-core/lib/index.js:57:18)
    at /Users/eritislami/evobot/node_modules/ytdl-core/lib/index.js:18:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
