### ISSUE TITLE
Error: Status Code: 404

### ISSUE THREAD

**Issue by ghost** [amishshah/ytdl-core-discord#367]
For a few hours everyone I know who uses this library is suffering from the same error. Please fix it how long

**Comment by DarkPlayer2** [comment]
I think that Module is Deprecated

**Comment by taroshg** [comment]
its an issue with the ytdl-core lib/info.js, where the access to the youtube get_video_info API was broken.
[https://github.com/fent/node-ytdl-core/commit/d1f535712410eebd79a7468abd07d94f8c4ebe5a](https://github.com/fent/node-ytdl-core/commit/d1f535712410eebd79a7468abd07d94f8c4ebe5a)

**Comment by Ddongddi** [comment]
I got this status message too...
Anyone know how to solve this?

**Comment by WallopingEwe** [comment]
Same here

`MinigetError: Status code: 404
    at ClientRequest.<anonymous> (/home/runner/Fascism/node_modules/miniget/dist/index.js:211:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12) {
  statusCode: 404
}`

**Comment by Noobslayer123** [comment]
i'm having the same issue, ytdl-core-discord only plays certain videos

**Comment by keksgauner** [comment]
its on yt side

**Comment by WallopingEwe** [comment]
ytdl-core patched the 404 errors

**Comment by JakeWymer** [comment]
I just opened up a PR to bump the version of ytdl-core that we use(https://github.com/amishshah/ytdl-core-discord/pull/368)

**Comment by ghost** [comment]
This is an issue with ytdl-core itself, update it to the latest version and it should be fixed.
Until #368 is merged, run the command:
`npm i ytdl-core@latest`
